export const OPEN_PIZZA_MODAL = "OPEN_PIZZA_MODAL";
export const CHANGE_PIZZA_SIZE = "CHANGE_PIZZA_SIZE";
export const REMOVE_PIZZA_INGREDIENT = "REMOVE_PIZZA_INGREDIENT";
export const RETURN_DELETED_PIZZA_INGREDIENT =
  "RETURN_DELETED_PIZZA_INGREDIENT";
