// CART TYPES
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const GET_CART = "GET_CART";
export const INCREMENT_QUANTITY = "INCREMENT_QUANTITY";
export const DECREMENT_QUANTITY = "DECREMENT_QUANTITY";
