// PIZZAS TYPES
export const GET_PIZZAS = "GET_PIZZAS";
export const GET_PIZZA_INGREDIENTS = "GET_PIZZA_INGREDIENTS";

// PIZZA MODAL TYPES
export const OPEN_PIZZA_MODAL = "OPEN_PIZZA_MODAL";
export const HIDE_PIZZA_MODAL = "HIDE_PIZZA_MODAL";
export const CHANGE_PIZZA_SIZE = "CHANGE_PIZZA_SIZE";
export const CHANGE_PIZZA_DOUGH = "CHANGE_PIZZA_DOUGH";
export const REMOVE_PIZZA_INGREDIENT = "REMOVE_PIZZA_INGREDIENT";
export const RETURN_DELETED_PIZZA_INGREDIENT =
  "RETURN_DELETED_PIZZA_INGREDIENT";
export const ADD_EXTRA_PIZZA_INGREDIENT = "ADD_EXTRA_PIZZA_INGREDIENT";
export const REMOVE_EXTRA_PIZZA_INGREDIENT = "REMOVE_EXTRA_PIZZA_INGREDIENT";
export const ADD_EXTRA_FANTAZY_PIZZA_INGREDIENT =
  "ADD_EXTRA_FANTAZY_PIZZA_INGREDIENT";
export const REMOVE_EXTRA_FANTAZY_PIZZA_INGREDIENT =
  "REMOVE_EXTRA_FANTAZY_PIZZA_INGREDIENT";

// CART TYPES
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const GET_CART = "GET_CART";
export const INCREMENT_QUANTITY = "INCREMENT_QUANTITY";
